# Generated by Django 4.2 on 2025-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbhiruchiWebsite', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
